package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CasetasCombinadasId generated by hbm2java
 */
@Embeddable
public class CasetasCombinadasId implements java.io.Serializable {

	private String coordX;
	private String coordY;
	private int idCaseta;
	private String nombre;
	private Short tipo;

	public CasetasCombinadasId() {
	}

	public CasetasCombinadasId(int idCaseta) {
		this.idCaseta = idCaseta;
	}

	public CasetasCombinadasId(String coordX, String coordY, int idCaseta,
			String nombre, Short tipo) {
		this.coordX = coordX;
		this.coordY = coordY;
		this.idCaseta = idCaseta;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	@Column(name = "coord_x", length = 50)
	public String getCoordX() {
		return this.coordX;
	}

	public void setCoordX(String coordX) {
		this.coordX = coordX;
	}

	@Column(name = "coord_y", length = 50)
	public String getCoordY() {
		return this.coordY;
	}

	public void setCoordY(String coordY) {
		this.coordY = coordY;
	}

	@Column(name = "id_caseta", nullable = false)
	public int getIdCaseta() {
		return this.idCaseta;
	}

	public void setIdCaseta(int idCaseta) {
		this.idCaseta = idCaseta;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "tipo")
	public Short getTipo() {
		return this.tipo;
	}

	public void setTipo(Short tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CasetasCombinadasId))
			return false;
		CasetasCombinadasId castOther = (CasetasCombinadasId) other;

		return ((this.getCoordX() == castOther.getCoordX()) || (this
				.getCoordX() != null && castOther.getCoordX() != null && this
				.getCoordX().equals(castOther.getCoordX())))
				&& ((this.getCoordY() == castOther.getCoordY()) || (this
						.getCoordY() != null && castOther.getCoordY() != null && this
						.getCoordY().equals(castOther.getCoordY())))
				&& (this.getIdCaseta() == castOther.getIdCaseta())
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCoordX() == null ? 0 : this.getCoordX().hashCode());
		result = 37 * result
				+ (getCoordY() == null ? 0 : this.getCoordY().hashCode());
		result = 37 * result + this.getIdCaseta();
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
