package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasetasCombinadas generated by hbm2java
 */
@Entity
@Table(name = "casetas_combinadas", catalog = "rutadb")
public class CasetasCombinadas implements java.io.Serializable {

	private CasetasCombinadasId id;

	public CasetasCombinadas() {
	}

	public CasetasCombinadas(CasetasCombinadasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "coordX", column = @Column(name = "coord_x", length = 50)),
			@AttributeOverride(name = "coordY", column = @Column(name = "coord_y", length = 50)),
			@AttributeOverride(name = "idCaseta", column = @Column(name = "id_caseta", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 150)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo")) })
	public CasetasCombinadasId getId() {
		return this.id;
	}

	public void setId(CasetasCombinadasId id) {
		this.id = id;
	}

}
