package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasetasSencillas generated by hbm2java
 */
@Entity
@Table(name = "casetas_sencillas", catalog = "rutadb")
public class CasetasSencillas implements java.io.Serializable {

	private CasetasSencillasId id;

	public CasetasSencillas() {
	}

	public CasetasSencillas(CasetasSencillasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "coordX", column = @Column(name = "coord_x", length = 50)),
			@AttributeOverride(name = "coordY", column = @Column(name = "coord_y", length = 50)),
			@AttributeOverride(name = "idCaseta", column = @Column(name = "id_caseta", nullable = false)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 150)),
			@AttributeOverride(name = "via", column = @Column(name = "via", length = 150)),
			@AttributeOverride(name = "longKm", column = @Column(name = "long_km", precision = 8, scale = 3)),
			@AttributeOverride(name = "km", column = @Column(name = "km", length = 50)),
			@AttributeOverride(name = "vigenteDe", column = @Column(name = "vigente_de", length = 2047)),
			@AttributeOverride(name = "motos", column = @Column(name = "motos")),
			@AttributeOverride(name = "autos", column = @Column(name = "autos")),
			@AttributeOverride(name = "ab2ejes", column = @Column(name = "ab2ejes")),
			@AttributeOverride(name = "ab3ejes", column = @Column(name = "ab3ejes")),
			@AttributeOverride(name = "ab4ejes", column = @Column(name = "ab4ejes")),
			@AttributeOverride(name = "cm2ejes", column = @Column(name = "cm2ejes")),
			@AttributeOverride(name = "cm3ejes", column = @Column(name = "cm3ejes")),
			@AttributeOverride(name = "cm4ejes", column = @Column(name = "cm4ejes")),
			@AttributeOverride(name = "cm5ejes", column = @Column(name = "cm5ejes")),
			@AttributeOverride(name = "cm6ejes", column = @Column(name = "cm6ejes")),
			@AttributeOverride(name = "cm7ejes", column = @Column(name = "cm7ejes")),
			@AttributeOverride(name = "cm8ejes", column = @Column(name = "cm8ejes")),
			@AttributeOverride(name = "cm9ejes", column = @Column(name = "cm9ejes")),
			@AttributeOverride(name = "vigenciaTarifa", column = @Column(name = "vigencia_tarifa", length = 0)),
			@AttributeOverride(name = "x", column = @Column(name = "x", precision = 22, scale = 0)),
			@AttributeOverride(name = "y", column = @Column(name = "y", precision = 13, scale = 8)) })
	public CasetasSencillasId getId() {
		return this.id;
	}

	public void setId(CasetasSencillasId id) {
		this.id = id;
	}

}
