package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CasetasSencillasN generated by hbm2java
 */
@Entity
@Table(name = "casetas_sencillas_n", catalog = "rutadb")
public class CasetasSencillasN implements java.io.Serializable {

	private CasetasSencillasNId id;

	public CasetasSencillasN() {
	}

	public CasetasSencillasN(CasetasSencillasNId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idCaseta", column = @Column(name = "id_caseta", length = 0)),
			@AttributeOverride(name = "gid", column = @Column(name = "gid", length = 0)) })
	public CasetasSencillasNId getId() {
		return this.id;
	}

	public void setId(CasetasSencillasNId id) {
		this.id = id;
	}

}
