package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CostosCasetasCombinadas generated by hbm2java
 */
@Entity
@Table(name = "costos_casetas_combinadas", catalog = "rutadb")
public class CostosCasetasCombinadas implements java.io.Serializable {

	private CostosCasetasCombinadasId id;

	public CostosCasetasCombinadas() {
	}

	public CostosCasetasCombinadas(CostosCasetasCombinadasId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEntrada", column = @Column(name = "id_entrada", length = 4)),
			@AttributeOverride(name = "idSalida", column = @Column(name = "id_salida", length = 4)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", length = 60)),
			@AttributeOverride(name = "tramo", column = @Column(name = "tramo", length = 59)),
			@AttributeOverride(name = "longKm", column = @Column(name = "long_km", length = 8)),
			@AttributeOverride(name = "vigenteDesde", column = @Column(name = "vigente_desde", length = 14)),
			@AttributeOverride(name = "motos", column = @Column(name = "motos", length = 6)),
			@AttributeOverride(name = "auto", column = @Column(name = "auto", length = 6)),
			@AttributeOverride(name = "ab2ejes", column = @Column(name = "ab2ejes", length = 9)),
			@AttributeOverride(name = "ab3ejes", column = @Column(name = "ab3ejes", length = 9)),
			@AttributeOverride(name = "ab4ejes", column = @Column(name = "ab4ejes", length = 9)),
			@AttributeOverride(name = "cm2ejes", column = @Column(name = "cm2ejes", length = 9)),
			@AttributeOverride(name = "cm3ejes", column = @Column(name = "cm3ejes", length = 9)),
			@AttributeOverride(name = "cm4ejes", column = @Column(name = "cm4ejes", length = 9)),
			@AttributeOverride(name = "cm5ejes", column = @Column(name = "cm5ejes", length = 9)),
			@AttributeOverride(name = "cm6ejes", column = @Column(name = "cm6ejes", length = 9)),
			@AttributeOverride(name = "cm7ejes", column = @Column(name = "cm7ejes", length = 9)),
			@AttributeOverride(name = "cm8ejes", column = @Column(name = "cm8ejes", length = 9)),
			@AttributeOverride(name = "cm9ejes", column = @Column(name = "cm9ejes", length = 9)) })
	public CostosCasetasCombinadasId getId() {
		return this.id;
	}

	public void setId(CostosCasetasCombinadasId id) {
		this.id = id;
	}

}
