package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * RuleStep1Id generated by hbm2java
 */
@Embeddable
public class RuleStep1Id implements java.io.Serializable {

	private Long gid;
	private String nombre;
	private Double idCarr;
	private Double idRed1;
	private Double idRed2;
	private Long gidRule;

	public RuleStep1Id() {
	}

	public RuleStep1Id(Long gid, String nombre, Double idCarr, Double idRed1,
			Double idRed2, Long gidRule) {
		this.gid = gid;
		this.nombre = nombre;
		this.idCarr = idCarr;
		this.idRed1 = idRed1;
		this.idRed2 = idRed2;
		this.gidRule = gidRule;
	}

	@Column(name = "gid")
	public Long getGid() {
		return this.gid;
	}

	public void setGid(Long gid) {
		this.gid = gid;
	}

	@Column(name = "nombre", length = 120)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "id_carr", precision = 22, scale = 0)
	public Double getIdCarr() {
		return this.idCarr;
	}

	public void setIdCarr(Double idCarr) {
		this.idCarr = idCarr;
	}

	@Column(name = "id_red1", precision = 22, scale = 0)
	public Double getIdRed1() {
		return this.idRed1;
	}

	public void setIdRed1(Double idRed1) {
		this.idRed1 = idRed1;
	}

	@Column(name = "id_red2", precision = 22, scale = 0)
	public Double getIdRed2() {
		return this.idRed2;
	}

	public void setIdRed2(Double idRed2) {
		this.idRed2 = idRed2;
	}

	@Column(name = "gid_rule")
	public Long getGidRule() {
		return this.gidRule;
	}

	public void setGidRule(Long gidRule) {
		this.gidRule = gidRule;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RuleStep1Id))
			return false;
		RuleStep1Id castOther = (RuleStep1Id) other;

		return ((this.getGid() == castOther.getGid()) || (this.getGid() != null
				&& castOther.getGid() != null && this.getGid().equals(
				castOther.getGid())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getIdCarr() == castOther.getIdCarr()) || (this
						.getIdCarr() != null && castOther.getIdCarr() != null && this
						.getIdCarr().equals(castOther.getIdCarr())))
				&& ((this.getIdRed1() == castOther.getIdRed1()) || (this
						.getIdRed1() != null && castOther.getIdRed1() != null && this
						.getIdRed1().equals(castOther.getIdRed1())))
				&& ((this.getIdRed2() == castOther.getIdRed2()) || (this
						.getIdRed2() != null && castOther.getIdRed2() != null && this
						.getIdRed2().equals(castOther.getIdRed2())))
				&& ((this.getGidRule() == castOther.getGidRule()) || (this
						.getGidRule() != null && castOther.getGidRule() != null && this
						.getGidRule().equals(castOther.getGidRule())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getGid() == null ? 0 : this.getGid().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result
				+ (getIdCarr() == null ? 0 : this.getIdCarr().hashCode());
		result = 37 * result
				+ (getIdRed1() == null ? 0 : this.getIdRed1().hashCode());
		result = 37 * result
				+ (getIdRed2() == null ? 0 : this.getIdRed2().hashCode());
		result = 37 * result
				+ (getGidRule() == null ? 0 : this.getGidRule().hashCode());
		return result;
	}

}
