package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * RuleStep1 generated by hbm2java
 */
@Entity
@Table(name = "rule_step1", catalog = "rutadb")
public class RuleStep1 implements java.io.Serializable {

	private RuleStep1Id id;

	public RuleStep1() {
	}

	public RuleStep1(RuleStep1Id id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "gid", column = @Column(name = "gid")),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 120)),
			@AttributeOverride(name = "idCarr", column = @Column(name = "id_carr", precision = 22, scale = 0)),
			@AttributeOverride(name = "idRed1", column = @Column(name = "id_red1", precision = 22, scale = 0)),
			@AttributeOverride(name = "idRed2", column = @Column(name = "id_red2", precision = 22, scale = 0)),
			@AttributeOverride(name = "gidRule", column = @Column(name = "gid_rule")) })
	public RuleStep1Id getId() {
		return this.id;
	}

	public void setId(RuleStep1Id id) {
		this.id = id;
	}

}
