package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TtrAodAmbitoBusqueda generated by hbm2java
 */
@Entity
@Table(name = "ttr_aod_ambito_busqueda", catalog = "rutadb")
public class TtrAodAmbitoBusqueda implements java.io.Serializable {

	private int idAmbitoBusqueda;
	private TtrAodTipoGeometrias ttrAodTipoGeometrias;
	private String descripcion;
	private String nombreTabla;
	private String nombreCampoClave;
	private String nombreCampoGeom;
	private String nombreCampoDesc;
	private String nombreCampoX;
	private String nombreCampoY;
	private Long hits;
	private Set<TtrAodReglasBusqueda> ttrAodReglasBusquedas = new HashSet<TtrAodReglasBusqueda>(
			0);
	private Set<TtrAodAmbitosRegla> ttrAodAmbitosReglas = new HashSet<TtrAodAmbitosRegla>(
			0);
	private Set<TtrAodJerarquiasAmbito> ttrAodJerarquiasAmbitos = new HashSet<TtrAodJerarquiasAmbito>(
			0);

	public TtrAodAmbitoBusqueda() {
	}

	public TtrAodAmbitoBusqueda(int idAmbitoBusqueda) {
		this.idAmbitoBusqueda = idAmbitoBusqueda;
	}

	public TtrAodAmbitoBusqueda(int idAmbitoBusqueda,
			TtrAodTipoGeometrias ttrAodTipoGeometrias, String descripcion,
			String nombreTabla, String nombreCampoClave,
			String nombreCampoGeom, String nombreCampoDesc,
			String nombreCampoX, String nombreCampoY, Long hits,
			Set<TtrAodReglasBusqueda> ttrAodReglasBusquedas,
			Set<TtrAodAmbitosRegla> ttrAodAmbitosReglas,
			Set<TtrAodJerarquiasAmbito> ttrAodJerarquiasAmbitos) {
		this.idAmbitoBusqueda = idAmbitoBusqueda;
		this.ttrAodTipoGeometrias = ttrAodTipoGeometrias;
		this.descripcion = descripcion;
		this.nombreTabla = nombreTabla;
		this.nombreCampoClave = nombreCampoClave;
		this.nombreCampoGeom = nombreCampoGeom;
		this.nombreCampoDesc = nombreCampoDesc;
		this.nombreCampoX = nombreCampoX;
		this.nombreCampoY = nombreCampoY;
		this.hits = hits;
		this.ttrAodReglasBusquedas = ttrAodReglasBusquedas;
		this.ttrAodAmbitosReglas = ttrAodAmbitosReglas;
		this.ttrAodJerarquiasAmbitos = ttrAodJerarquiasAmbitos;
	}

	@Id
	@Column(name = "id_ambito_busqueda", unique = true, nullable = false)
	public int getIdAmbitoBusqueda() {
		return this.idAmbitoBusqueda;
	}

	public void setIdAmbitoBusqueda(int idAmbitoBusqueda) {
		this.idAmbitoBusqueda = idAmbitoBusqueda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_tipo_geometria")
	public TtrAodTipoGeometrias getTtrAodTipoGeometrias() {
		return this.ttrAodTipoGeometrias;
	}

	public void setTtrAodTipoGeometrias(
			TtrAodTipoGeometrias ttrAodTipoGeometrias) {
		this.ttrAodTipoGeometrias = ttrAodTipoGeometrias;
	}

	@Column(name = "descripcion", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "nombre_tabla", length = 100)
	public String getNombreTabla() {
		return this.nombreTabla;
	}

	public void setNombreTabla(String nombreTabla) {
		this.nombreTabla = nombreTabla;
	}

	@Column(name = "nombre_campo_clave", length = 60)
	public String getNombreCampoClave() {
		return this.nombreCampoClave;
	}

	public void setNombreCampoClave(String nombreCampoClave) {
		this.nombreCampoClave = nombreCampoClave;
	}

	@Column(name = "nombre_campo_geom", length = 60)
	public String getNombreCampoGeom() {
		return this.nombreCampoGeom;
	}

	public void setNombreCampoGeom(String nombreCampoGeom) {
		this.nombreCampoGeom = nombreCampoGeom;
	}

	@Column(name = "nombre_campo_desc", length = 60)
	public String getNombreCampoDesc() {
		return this.nombreCampoDesc;
	}

	public void setNombreCampoDesc(String nombreCampoDesc) {
		this.nombreCampoDesc = nombreCampoDesc;
	}

	@Column(name = "nombre_campo_x", length = 60)
	public String getNombreCampoX() {
		return this.nombreCampoX;
	}

	public void setNombreCampoX(String nombreCampoX) {
		this.nombreCampoX = nombreCampoX;
	}

	@Column(name = "nombre_campo_y", length = 60)
	public String getNombreCampoY() {
		return this.nombreCampoY;
	}

	public void setNombreCampoY(String nombreCampoY) {
		this.nombreCampoY = nombreCampoY;
	}

	@Column(name = "hits")
	public Long getHits() {
		return this.hits;
	}

	public void setHits(Long hits) {
		this.hits = hits;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrAodAmbitoBusqueda")
	public Set<TtrAodReglasBusqueda> getTtrAodReglasBusquedas() {
		return this.ttrAodReglasBusquedas;
	}

	public void setTtrAodReglasBusquedas(
			Set<TtrAodReglasBusqueda> ttrAodReglasBusquedas) {
		this.ttrAodReglasBusquedas = ttrAodReglasBusquedas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrAodAmbitoBusqueda")
	public Set<TtrAodAmbitosRegla> getTtrAodAmbitosReglas() {
		return this.ttrAodAmbitosReglas;
	}

	public void setTtrAodAmbitosReglas(
			Set<TtrAodAmbitosRegla> ttrAodAmbitosReglas) {
		this.ttrAodAmbitosReglas = ttrAodAmbitosReglas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrAodAmbitoBusqueda")
	public Set<TtrAodJerarquiasAmbito> getTtrAodJerarquiasAmbitos() {
		return this.ttrAodJerarquiasAmbitos;
	}

	public void setTtrAodJerarquiasAmbitos(
			Set<TtrAodJerarquiasAmbito> ttrAodJerarquiasAmbitos) {
		this.ttrAodJerarquiasAmbitos = ttrAodJerarquiasAmbitos;
	}

}
