package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TtrAodSearchesCache generated by hbm2java
 */
@Entity
@Table(name = "ttr_aod_searches_cache", catalog = "rutadb")
public class TtrAodSearchesCache implements java.io.Serializable {

	private TtrAodSearchesCacheId id;

	public TtrAodSearchesCache() {
	}

	public TtrAodSearchesCache(TtrAodSearchesCacheId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "patternSearch", column = @Column(name = "pattern_search", length = 100)),
			@AttributeOverride(name = "patternSearchResult", column = @Column(name = "pattern_search_result", length = 100)),
			@AttributeOverride(name = "dateAdded", column = @Column(name = "date_added", length = 0)) })
	public TtrAodSearchesCacheId getId() {
		return this.id;
	}

	public void setId(TtrAodSearchesCacheId id) {
		this.id = id;
	}

}
