package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrAodSearchesCacheId generated by hbm2java
 */
@Embeddable
public class TtrAodSearchesCacheId implements java.io.Serializable {

	private String patternSearch;
	private String patternSearchResult;
	private Date dateAdded;

	public TtrAodSearchesCacheId() {
	}

	public TtrAodSearchesCacheId(String patternSearch,
			String patternSearchResult, Date dateAdded) {
		this.patternSearch = patternSearch;
		this.patternSearchResult = patternSearchResult;
		this.dateAdded = dateAdded;
	}

	@Column(name = "pattern_search", length = 100)
	public String getPatternSearch() {
		return this.patternSearch;
	}

	public void setPatternSearch(String patternSearch) {
		this.patternSearch = patternSearch;
	}

	@Column(name = "pattern_search_result", length = 100)
	public String getPatternSearchResult() {
		return this.patternSearchResult;
	}

	public void setPatternSearchResult(String patternSearchResult) {
		this.patternSearchResult = patternSearchResult;
	}

	@Column(name = "date_added", length = 0)
	public Date getDateAdded() {
		return this.dateAdded;
	}

	public void setDateAdded(Date dateAdded) {
		this.dateAdded = dateAdded;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrAodSearchesCacheId))
			return false;
		TtrAodSearchesCacheId castOther = (TtrAodSearchesCacheId) other;

		return ((this.getPatternSearch() == castOther.getPatternSearch()) || (this
				.getPatternSearch() != null
				&& castOther.getPatternSearch() != null && this
				.getPatternSearch().equals(castOther.getPatternSearch())))
				&& ((this.getPatternSearchResult() == castOther
						.getPatternSearchResult()) || (this
						.getPatternSearchResult() != null
						&& castOther.getPatternSearchResult() != null && this
						.getPatternSearchResult().equals(
								castOther.getPatternSearchResult())))
				&& ((this.getDateAdded() == castOther.getDateAdded()) || (this
						.getDateAdded() != null
						&& castOther.getDateAdded() != null && this
						.getDateAdded().equals(castOther.getDateAdded())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getPatternSearch() == null ? 0 : this.getPatternSearch()
						.hashCode());
		result = 37
				* result
				+ (getPatternSearchResult() == null ? 0 : this
						.getPatternSearchResult().hashCode());
		result = 37 * result
				+ (getDateAdded() == null ? 0 : this.getDateAdded().hashCode());
		return result;
	}

}
