package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrAodAmbitosReglaId generated by hbm2java
 */
@Embeddable
public class TtrAodAmbitosReglaId implements java.io.Serializable {

	private Integer fkIdRegla;
	private Integer noJerarquia;
	private Integer fkIdAmbitoBusqueda;
	private String campoClaveAmbitoJerarquico;
	private String campoNombreAmbitoJerarquico;

	public TtrAodAmbitosReglaId() {
	}

	public TtrAodAmbitosReglaId(Integer fkIdRegla, Integer noJerarquia,
			Integer fkIdAmbitoBusqueda, String campoClaveAmbitoJerarquico,
			String campoNombreAmbitoJerarquico) {
		this.fkIdRegla = fkIdRegla;
		this.noJerarquia = noJerarquia;
		this.fkIdAmbitoBusqueda = fkIdAmbitoBusqueda;
		this.campoClaveAmbitoJerarquico = campoClaveAmbitoJerarquico;
		this.campoNombreAmbitoJerarquico = campoNombreAmbitoJerarquico;
	}

	@Column(name = "fk_id_regla")
	public Integer getFkIdRegla() {
		return this.fkIdRegla;
	}

	public void setFkIdRegla(Integer fkIdRegla) {
		this.fkIdRegla = fkIdRegla;
	}

	@Column(name = "no_jerarquia")
	public Integer getNoJerarquia() {
		return this.noJerarquia;
	}

	public void setNoJerarquia(Integer noJerarquia) {
		this.noJerarquia = noJerarquia;
	}

	@Column(name = "fk_id_ambito_busqueda")
	public Integer getFkIdAmbitoBusqueda() {
		return this.fkIdAmbitoBusqueda;
	}

	public void setFkIdAmbitoBusqueda(Integer fkIdAmbitoBusqueda) {
		this.fkIdAmbitoBusqueda = fkIdAmbitoBusqueda;
	}

	@Column(name = "campo_clave_ambito_jerarquico", length = 60)
	public String getCampoClaveAmbitoJerarquico() {
		return this.campoClaveAmbitoJerarquico;
	}

	public void setCampoClaveAmbitoJerarquico(String campoClaveAmbitoJerarquico) {
		this.campoClaveAmbitoJerarquico = campoClaveAmbitoJerarquico;
	}

	@Column(name = "campo_nombre_ambito_jerarquico", length = 80)
	public String getCampoNombreAmbitoJerarquico() {
		return this.campoNombreAmbitoJerarquico;
	}

	public void setCampoNombreAmbitoJerarquico(
			String campoNombreAmbitoJerarquico) {
		this.campoNombreAmbitoJerarquico = campoNombreAmbitoJerarquico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrAodAmbitosReglaId))
			return false;
		TtrAodAmbitosReglaId castOther = (TtrAodAmbitosReglaId) other;

		return ((this.getFkIdRegla() == castOther.getFkIdRegla()) || (this
				.getFkIdRegla() != null && castOther.getFkIdRegla() != null && this
				.getFkIdRegla().equals(castOther.getFkIdRegla())))
				&& ((this.getNoJerarquia() == castOther.getNoJerarquia()) || (this
						.getNoJerarquia() != null
						&& castOther.getNoJerarquia() != null && this
						.getNoJerarquia().equals(castOther.getNoJerarquia())))
				&& ((this.getFkIdAmbitoBusqueda() == castOther
						.getFkIdAmbitoBusqueda()) || (this
						.getFkIdAmbitoBusqueda() != null
						&& castOther.getFkIdAmbitoBusqueda() != null && this
						.getFkIdAmbitoBusqueda().equals(
								castOther.getFkIdAmbitoBusqueda())))
				&& ((this.getCampoClaveAmbitoJerarquico() == castOther
						.getCampoClaveAmbitoJerarquico()) || (this
						.getCampoClaveAmbitoJerarquico() != null
						&& castOther.getCampoClaveAmbitoJerarquico() != null && this
						.getCampoClaveAmbitoJerarquico().equals(
								castOther.getCampoClaveAmbitoJerarquico())))
				&& ((this.getCampoNombreAmbitoJerarquico() == castOther
						.getCampoNombreAmbitoJerarquico()) || (this
						.getCampoNombreAmbitoJerarquico() != null
						&& castOther.getCampoNombreAmbitoJerarquico() != null && this
						.getCampoNombreAmbitoJerarquico().equals(
								castOther.getCampoNombreAmbitoJerarquico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getFkIdRegla() == null ? 0 : this.getFkIdRegla().hashCode());
		result = 37
				* result
				+ (getNoJerarquia() == null ? 0 : this.getNoJerarquia()
						.hashCode());
		result = 37
				* result
				+ (getFkIdAmbitoBusqueda() == null ? 0 : this
						.getFkIdAmbitoBusqueda().hashCode());
		result = 37
				* result
				+ (getCampoClaveAmbitoJerarquico() == null ? 0 : this
						.getCampoClaveAmbitoJerarquico().hashCode());
		result = 37
				* result
				+ (getCampoNombreAmbitoJerarquico() == null ? 0 : this
						.getCampoNombreAmbitoJerarquico().hashCode());
		return result;
	}

}
