package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TtrAodAmbitosRegla generated by hbm2java
 */
@Entity
@Table(name = "ttr_aod_ambitos_regla", catalog = "rutadb")
public class TtrAodAmbitosRegla implements java.io.Serializable {

	private TtrAodAmbitosReglaId id;
	private TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda;

	public TtrAodAmbitosRegla() {
	}

	public TtrAodAmbitosRegla(TtrAodAmbitosReglaId id) {
		this.id = id;
	}

	public TtrAodAmbitosRegla(TtrAodAmbitosReglaId id,
			TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda) {
		this.id = id;
		this.ttrAodAmbitoBusqueda = ttrAodAmbitoBusqueda;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fkIdRegla", column = @Column(name = "fk_id_regla")),
			@AttributeOverride(name = "noJerarquia", column = @Column(name = "no_jerarquia")),
			@AttributeOverride(name = "fkIdAmbitoBusqueda", column = @Column(name = "fk_id_ambito_busqueda")),
			@AttributeOverride(name = "campoClaveAmbitoJerarquico", column = @Column(name = "campo_clave_ambito_jerarquico", length = 60)),
			@AttributeOverride(name = "campoNombreAmbitoJerarquico", column = @Column(name = "campo_nombre_ambito_jerarquico", length = 80)) })
	public TtrAodAmbitosReglaId getId() {
		return this.id;
	}

	public void setId(TtrAodAmbitosReglaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_ambito_busqueda", insertable = false, updatable = false)
	public TtrAodAmbitoBusqueda getTtrAodAmbitoBusqueda() {
		return this.ttrAodAmbitoBusqueda;
	}

	public void setTtrAodAmbitoBusqueda(
			TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda) {
		this.ttrAodAmbitoBusqueda = ttrAodAmbitoBusqueda;
	}

}
