package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TtrAodReglasBusqueda generated by hbm2java
 */
@Entity
@Table(name = "ttr_aod_reglas_busqueda", catalog = "rutadb")
public class TtrAodReglasBusqueda implements java.io.Serializable {

	private int idReglaBusqueda;
	private TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda;
	private String nombre;
	private Integer prioridad;
	private Integer noCommas;
	private Long hits;
	private Boolean estatus;

	public TtrAodReglasBusqueda() {
	}

	public TtrAodReglasBusqueda(int idReglaBusqueda) {
		this.idReglaBusqueda = idReglaBusqueda;
	}

	public TtrAodReglasBusqueda(int idReglaBusqueda,
			TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda, String nombre,
			Integer prioridad, Integer noCommas, Long hits, Boolean estatus) {
		this.idReglaBusqueda = idReglaBusqueda;
		this.ttrAodAmbitoBusqueda = ttrAodAmbitoBusqueda;
		this.nombre = nombre;
		this.prioridad = prioridad;
		this.noCommas = noCommas;
		this.hits = hits;
		this.estatus = estatus;
	}

	@Id
	@Column(name = "id_regla_busqueda", unique = true, nullable = false)
	public int getIdReglaBusqueda() {
		return this.idReglaBusqueda;
	}

	public void setIdReglaBusqueda(int idReglaBusqueda) {
		this.idReglaBusqueda = idReglaBusqueda;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_ambito_busqueda")
	public TtrAodAmbitoBusqueda getTtrAodAmbitoBusqueda() {
		return this.ttrAodAmbitoBusqueda;
	}

	public void setTtrAodAmbitoBusqueda(
			TtrAodAmbitoBusqueda ttrAodAmbitoBusqueda) {
		this.ttrAodAmbitoBusqueda = ttrAodAmbitoBusqueda;
	}

	@Column(name = "nombre", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "prioridad")
	public Integer getPrioridad() {
		return this.prioridad;
	}

	public void setPrioridad(Integer prioridad) {
		this.prioridad = prioridad;
	}

	@Column(name = "no_commas")
	public Integer getNoCommas() {
		return this.noCommas;
	}

	public void setNoCommas(Integer noCommas) {
		this.noCommas = noCommas;
	}

	@Column(name = "hits")
	public Long getHits() {
		return this.hits;
	}

	public void setHits(Long hits) {
		this.hits = hits;
	}

	@Column(name = "estatus")
	public Boolean getEstatus() {
		return this.estatus;
	}

	public void setEstatus(Boolean estatus) {
		this.estatus = estatus;
	}

}
