package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrAodJerarquiasAmbitoId generated by hbm2java
 */
@Embeddable
public class TtrAodJerarquiasAmbitoId implements java.io.Serializable {

	private Integer fkIdAmbitoBusqueda;
	private Integer noJerarquia;
	private Integer fkIdAmbitoBusquedaJerarquia;
	private String campoClaveAmbitoJerarquico;
	private String campoNombreAmbitoJerarquico;

	public TtrAodJerarquiasAmbitoId() {
	}

	public TtrAodJerarquiasAmbitoId(Integer fkIdAmbitoBusqueda,
			Integer noJerarquia, Integer fkIdAmbitoBusquedaJerarquia,
			String campoClaveAmbitoJerarquico,
			String campoNombreAmbitoJerarquico) {
		this.fkIdAmbitoBusqueda = fkIdAmbitoBusqueda;
		this.noJerarquia = noJerarquia;
		this.fkIdAmbitoBusquedaJerarquia = fkIdAmbitoBusquedaJerarquia;
		this.campoClaveAmbitoJerarquico = campoClaveAmbitoJerarquico;
		this.campoNombreAmbitoJerarquico = campoNombreAmbitoJerarquico;
	}

	@Column(name = "fk_id_ambito_busqueda")
	public Integer getFkIdAmbitoBusqueda() {
		return this.fkIdAmbitoBusqueda;
	}

	public void setFkIdAmbitoBusqueda(Integer fkIdAmbitoBusqueda) {
		this.fkIdAmbitoBusqueda = fkIdAmbitoBusqueda;
	}

	@Column(name = "no_jerarquia")
	public Integer getNoJerarquia() {
		return this.noJerarquia;
	}

	public void setNoJerarquia(Integer noJerarquia) {
		this.noJerarquia = noJerarquia;
	}

	@Column(name = "fk_id_ambito_busqueda_jerarquia")
	public Integer getFkIdAmbitoBusquedaJerarquia() {
		return this.fkIdAmbitoBusquedaJerarquia;
	}

	public void setFkIdAmbitoBusquedaJerarquia(
			Integer fkIdAmbitoBusquedaJerarquia) {
		this.fkIdAmbitoBusquedaJerarquia = fkIdAmbitoBusquedaJerarquia;
	}

	@Column(name = "campo_clave_ambito_jerarquico", length = 60)
	public String getCampoClaveAmbitoJerarquico() {
		return this.campoClaveAmbitoJerarquico;
	}

	public void setCampoClaveAmbitoJerarquico(String campoClaveAmbitoJerarquico) {
		this.campoClaveAmbitoJerarquico = campoClaveAmbitoJerarquico;
	}

	@Column(name = "campo_nombre_ambito_jerarquico", length = 80)
	public String getCampoNombreAmbitoJerarquico() {
		return this.campoNombreAmbitoJerarquico;
	}

	public void setCampoNombreAmbitoJerarquico(
			String campoNombreAmbitoJerarquico) {
		this.campoNombreAmbitoJerarquico = campoNombreAmbitoJerarquico;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrAodJerarquiasAmbitoId))
			return false;
		TtrAodJerarquiasAmbitoId castOther = (TtrAodJerarquiasAmbitoId) other;

		return ((this.getFkIdAmbitoBusqueda() == castOther
				.getFkIdAmbitoBusqueda()) || (this.getFkIdAmbitoBusqueda() != null
				&& castOther.getFkIdAmbitoBusqueda() != null && this
				.getFkIdAmbitoBusqueda().equals(
						castOther.getFkIdAmbitoBusqueda())))
				&& ((this.getNoJerarquia() == castOther.getNoJerarquia()) || (this
						.getNoJerarquia() != null
						&& castOther.getNoJerarquia() != null && this
						.getNoJerarquia().equals(castOther.getNoJerarquia())))
				&& ((this.getFkIdAmbitoBusquedaJerarquia() == castOther
						.getFkIdAmbitoBusquedaJerarquia()) || (this
						.getFkIdAmbitoBusquedaJerarquia() != null
						&& castOther.getFkIdAmbitoBusquedaJerarquia() != null && this
						.getFkIdAmbitoBusquedaJerarquia().equals(
								castOther.getFkIdAmbitoBusquedaJerarquia())))
				&& ((this.getCampoClaveAmbitoJerarquico() == castOther
						.getCampoClaveAmbitoJerarquico()) || (this
						.getCampoClaveAmbitoJerarquico() != null
						&& castOther.getCampoClaveAmbitoJerarquico() != null && this
						.getCampoClaveAmbitoJerarquico().equals(
								castOther.getCampoClaveAmbitoJerarquico())))
				&& ((this.getCampoNombreAmbitoJerarquico() == castOther
						.getCampoNombreAmbitoJerarquico()) || (this
						.getCampoNombreAmbitoJerarquico() != null
						&& castOther.getCampoNombreAmbitoJerarquico() != null && this
						.getCampoNombreAmbitoJerarquico().equals(
								castOther.getCampoNombreAmbitoJerarquico())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getFkIdAmbitoBusqueda() == null ? 0 : this
						.getFkIdAmbitoBusqueda().hashCode());
		result = 37
				* result
				+ (getNoJerarquia() == null ? 0 : this.getNoJerarquia()
						.hashCode());
		result = 37
				* result
				+ (getFkIdAmbitoBusquedaJerarquia() == null ? 0 : this
						.getFkIdAmbitoBusquedaJerarquia().hashCode());
		result = 37
				* result
				+ (getCampoClaveAmbitoJerarquico() == null ? 0 : this
						.getCampoClaveAmbitoJerarquico().hashCode());
		result = 37
				* result
				+ (getCampoNombreAmbitoJerarquico() == null ? 0 : this
						.getCampoNombreAmbitoJerarquico().hashCode());
		return result;
	}

}
