package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrCostosCaseta generated by hbm2java
 */
@Entity
@Table(name = "ttr_costos_caseta", catalog = "rutadb")
public class TtrCostosCaseta implements java.io.Serializable {

	private Integer idCostoCaseta;
	private TtrSubTiposVehiculo ttrSubTiposVehiculo;
	private Integer idCaseta;
	private BigDecimal costoCaseta;
	private BigDecimal costoExcedenteCaseta;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;
	private Integer idTramoCaseta;

	public TtrCostosCaseta() {
	}

	public TtrCostosCaseta(TtrSubTiposVehiculo ttrSubTiposVehiculo,
			Integer idCaseta, BigDecimal costoCaseta,
			BigDecimal costoExcedenteCaseta, Date creadoEl, Date modificadoEl,
			String modificadoPor, Integer idTramoCaseta) {
		this.ttrSubTiposVehiculo = ttrSubTiposVehiculo;
		this.idCaseta = idCaseta;
		this.costoCaseta = costoCaseta;
		this.costoExcedenteCaseta = costoExcedenteCaseta;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
		this.idTramoCaseta = idTramoCaseta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_costo_caseta", unique = true, nullable = false)
	public Integer getIdCostoCaseta() {
		return this.idCostoCaseta;
	}

	public void setIdCostoCaseta(Integer idCostoCaseta) {
		this.idCostoCaseta = idCostoCaseta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sub_tipo_vehiculo")
	public TtrSubTiposVehiculo getTtrSubTiposVehiculo() {
		return this.ttrSubTiposVehiculo;
	}

	public void setTtrSubTiposVehiculo(TtrSubTiposVehiculo ttrSubTiposVehiculo) {
		this.ttrSubTiposVehiculo = ttrSubTiposVehiculo;
	}

	@Column(name = "id_caseta")
	public Integer getIdCaseta() {
		return this.idCaseta;
	}

	public void setIdCaseta(Integer idCaseta) {
		this.idCaseta = idCaseta;
	}

	@Column(name = "costo_caseta", precision = 10)
	public BigDecimal getCostoCaseta() {
		return this.costoCaseta;
	}

	public void setCostoCaseta(BigDecimal costoCaseta) {
		this.costoCaseta = costoCaseta;
	}

	@Column(name = "costo_excedente_caseta", precision = 10)
	public BigDecimal getCostoExcedenteCaseta() {
		return this.costoExcedenteCaseta;
	}

	public void setCostoExcedenteCaseta(BigDecimal costoExcedenteCaseta) {
		this.costoExcedenteCaseta = costoExcedenteCaseta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@Column(name = "id_tramo_caseta")
	public Integer getIdTramoCaseta() {
		return this.idTramoCaseta;
	}

	public void setIdTramoCaseta(Integer idTramoCaseta) {
		this.idTramoCaseta = idTramoCaseta;
	}

}
