package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrCostosCasetaCombinada generated by hbm2java
 */
@Entity
@Table(name = "ttr_costos_caseta_combinada", catalog = "rutadb")
public class TtrCostosCasetaCombinada implements java.io.Serializable {

	private Integer idCostoCasetaCombinada;
	private Integer fkIdCasetaCombinada;
	private Integer fkIdSubTipoVehiculo;
	private Integer fkIdCasetaCombinadaSalida;
	private BigDecimal costoCaseta;
	private BigDecimal costoExcedenteCaseta;

	public TtrCostosCasetaCombinada() {
	}

	public TtrCostosCasetaCombinada(Integer fkIdCasetaCombinada,
			Integer fkIdSubTipoVehiculo, Integer fkIdCasetaCombinadaSalida,
			BigDecimal costoCaseta, BigDecimal costoExcedenteCaseta) {
		this.fkIdCasetaCombinada = fkIdCasetaCombinada;
		this.fkIdSubTipoVehiculo = fkIdSubTipoVehiculo;
		this.fkIdCasetaCombinadaSalida = fkIdCasetaCombinadaSalida;
		this.costoCaseta = costoCaseta;
		this.costoExcedenteCaseta = costoExcedenteCaseta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_costo_caseta_combinada", unique = true, nullable = false)
	public Integer getIdCostoCasetaCombinada() {
		return this.idCostoCasetaCombinada;
	}

	public void setIdCostoCasetaCombinada(Integer idCostoCasetaCombinada) {
		this.idCostoCasetaCombinada = idCostoCasetaCombinada;
	}

	@Column(name = "fk_id_caseta_combinada")
	public Integer getFkIdCasetaCombinada() {
		return this.fkIdCasetaCombinada;
	}

	public void setFkIdCasetaCombinada(Integer fkIdCasetaCombinada) {
		this.fkIdCasetaCombinada = fkIdCasetaCombinada;
	}

	@Column(name = "fk_id_sub_tipo_vehiculo")
	public Integer getFkIdSubTipoVehiculo() {
		return this.fkIdSubTipoVehiculo;
	}

	public void setFkIdSubTipoVehiculo(Integer fkIdSubTipoVehiculo) {
		this.fkIdSubTipoVehiculo = fkIdSubTipoVehiculo;
	}

	@Column(name = "fk_id_caseta_combinada_salida")
	public Integer getFkIdCasetaCombinadaSalida() {
		return this.fkIdCasetaCombinadaSalida;
	}

	public void setFkIdCasetaCombinadaSalida(Integer fkIdCasetaCombinadaSalida) {
		this.fkIdCasetaCombinadaSalida = fkIdCasetaCombinadaSalida;
	}

	@Column(name = "costo_caseta", precision = 10)
	public BigDecimal getCostoCaseta() {
		return this.costoCaseta;
	}

	public void setCostoCaseta(BigDecimal costoCaseta) {
		this.costoCaseta = costoCaseta;
	}

	@Column(name = "costo_excedente_caseta", precision = 10)
	public BigDecimal getCostoExcedenteCaseta() {
		return this.costoExcedenteCaseta;
	}

	public void setCostoExcedenteCaseta(BigDecimal costoExcedenteCaseta) {
		this.costoExcedenteCaseta = costoExcedenteCaseta;
	}

}
