package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrEstacionesClimaId generated by hbm2java
 */
@Embeddable
public class TtrEstacionesClimaId implements java.io.Serializable {

	private String clave;
	private String nombre;
	private String x;
	private String y;
	private Double temph;
	private Double tmedia;
	private Double tmax;
	private Double tmin;
	private Double tobs;
	private String tipo;

	public TtrEstacionesClimaId() {
	}

	public TtrEstacionesClimaId(String clave, String nombre, String x,
			String y, Double temph, Double tmedia, Double tmax, Double tmin,
			Double tobs, String tipo) {
		this.clave = clave;
		this.nombre = nombre;
		this.x = x;
		this.y = y;
		this.temph = temph;
		this.tmedia = tmedia;
		this.tmax = tmax;
		this.tmin = tmin;
		this.tobs = tobs;
		this.tipo = tipo;
	}

	@Column(name = "clave", length = 30)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Column(name = "nombre", length = 254)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "x", length = 50)
	public String getX() {
		return this.x;
	}

	public void setX(String x) {
		this.x = x;
	}

	@Column(name = "y", length = 50)
	public String getY() {
		return this.y;
	}

	public void setY(String y) {
		this.y = y;
	}

	@Column(name = "temph", precision = 22, scale = 0)
	public Double getTemph() {
		return this.temph;
	}

	public void setTemph(Double temph) {
		this.temph = temph;
	}

	@Column(name = "tmedia", precision = 22, scale = 0)
	public Double getTmedia() {
		return this.tmedia;
	}

	public void setTmedia(Double tmedia) {
		this.tmedia = tmedia;
	}

	@Column(name = "tmax", precision = 22, scale = 0)
	public Double getTmax() {
		return this.tmax;
	}

	public void setTmax(Double tmax) {
		this.tmax = tmax;
	}

	@Column(name = "tmin", precision = 22, scale = 0)
	public Double getTmin() {
		return this.tmin;
	}

	public void setTmin(Double tmin) {
		this.tmin = tmin;
	}

	@Column(name = "tobs", precision = 22, scale = 0)
	public Double getTobs() {
		return this.tobs;
	}

	public void setTobs(Double tobs) {
		this.tobs = tobs;
	}

	@Column(name = "tipo", length = 1)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrEstacionesClimaId))
			return false;
		TtrEstacionesClimaId castOther = (TtrEstacionesClimaId) other;

		return ((this.getClave() == castOther.getClave()) || (this.getClave() != null
				&& castOther.getClave() != null && this.getClave().equals(
				castOther.getClave())))
				&& ((this.getNombre() == castOther.getNombre()) || (this
						.getNombre() != null && castOther.getNombre() != null && this
						.getNombre().equals(castOther.getNombre())))
				&& ((this.getX() == castOther.getX()) || (this.getX() != null
						&& castOther.getX() != null && this.getX().equals(
						castOther.getX())))
				&& ((this.getY() == castOther.getY()) || (this.getY() != null
						&& castOther.getY() != null && this.getY().equals(
						castOther.getY())))
				&& ((this.getTemph() == castOther.getTemph()) || (this
						.getTemph() != null && castOther.getTemph() != null && this
						.getTemph().equals(castOther.getTemph())))
				&& ((this.getTmedia() == castOther.getTmedia()) || (this
						.getTmedia() != null && castOther.getTmedia() != null && this
						.getTmedia().equals(castOther.getTmedia())))
				&& ((this.getTmax() == castOther.getTmax()) || (this.getTmax() != null
						&& castOther.getTmax() != null && this.getTmax()
						.equals(castOther.getTmax())))
				&& ((this.getTmin() == castOther.getTmin()) || (this.getTmin() != null
						&& castOther.getTmin() != null && this.getTmin()
						.equals(castOther.getTmin())))
				&& ((this.getTobs() == castOther.getTobs()) || (this.getTobs() != null
						&& castOther.getTobs() != null && this.getTobs()
						.equals(castOther.getTobs())))
				&& ((this.getTipo() == castOther.getTipo()) || (this.getTipo() != null
						&& castOther.getTipo() != null && this.getTipo()
						.equals(castOther.getTipo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getClave() == null ? 0 : this.getClave().hashCode());
		result = 37 * result
				+ (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getX() == null ? 0 : this.getX().hashCode());
		result = 37 * result + (getY() == null ? 0 : this.getY().hashCode());
		result = 37 * result
				+ (getTemph() == null ? 0 : this.getTemph().hashCode());
		result = 37 * result
				+ (getTmedia() == null ? 0 : this.getTmedia().hashCode());
		result = 37 * result
				+ (getTmax() == null ? 0 : this.getTmax().hashCode());
		result = 37 * result
				+ (getTmin() == null ? 0 : this.getTmin().hashCode());
		result = 37 * result
				+ (getTobs() == null ? 0 : this.getTobs().hashCode());
		result = 37 * result
				+ (getTipo() == null ? 0 : this.getTipo().hashCode());
		return result;
	}

}
