package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TtrEstacionesClima generated by hbm2java
 */
@Entity
@Table(name = "ttr_estaciones_clima", catalog = "rutadb")
public class TtrEstacionesClima implements java.io.Serializable {

	private TtrEstacionesClimaId id;

	public TtrEstacionesClima() {
	}

	public TtrEstacionesClima(TtrEstacionesClimaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "clave", column = @Column(name = "clave", length = 30)),
			@AttributeOverride(name = "nombre", column = @Column(name = "nombre", length = 254)),
			@AttributeOverride(name = "x", column = @Column(name = "x", length = 50)),
			@AttributeOverride(name = "y", column = @Column(name = "y", length = 50)),
			@AttributeOverride(name = "temph", column = @Column(name = "temph", precision = 22, scale = 0)),
			@AttributeOverride(name = "tmedia", column = @Column(name = "tmedia", precision = 22, scale = 0)),
			@AttributeOverride(name = "tmax", column = @Column(name = "tmax", precision = 22, scale = 0)),
			@AttributeOverride(name = "tmin", column = @Column(name = "tmin", precision = 22, scale = 0)),
			@AttributeOverride(name = "tobs", column = @Column(name = "tobs", precision = 22, scale = 0)),
			@AttributeOverride(name = "tipo", column = @Column(name = "tipo", length = 1)) })
	public TtrEstacionesClimaId getId() {
		return this.id;
	}

	public void setId(TtrEstacionesClimaId id) {
		this.id = id;
	}

}
