package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrIncidencia generated by hbm2java
 */
@Entity
@Table(name = "ttr_incidencia", catalog = "rutadb")
public class TtrIncidencia implements java.io.Serializable {

	private int incidenciaId;
	private Integer usuarioId;
	private String descripcion;
	private Character compartido;
	private Integer idTipo;
	private BigDecimal x;
	private BigDecimal y;

	public TtrIncidencia() {
	}

	public TtrIncidencia(int incidenciaId) {
		this.incidenciaId = incidenciaId;
	}

	public TtrIncidencia(int incidenciaId, Integer usuarioId,
			String descripcion, Character compartido, Integer idTipo,
			BigDecimal x, BigDecimal y) {
		this.incidenciaId = incidenciaId;
		this.usuarioId = usuarioId;
		this.descripcion = descripcion;
		this.compartido = compartido;
		this.idTipo = idTipo;
		this.x = x;
		this.y = y;
	}

	@Id
	@Column(name = "incidencia_id", unique = true, nullable = false)
	public int getIncidenciaId() {
		return this.incidenciaId;
	}

	public void setIncidenciaId(int incidenciaId) {
		this.incidenciaId = incidenciaId;
	}

	@Column(name = "usuario_id")
	public Integer getUsuarioId() {
		return this.usuarioId;
	}

	public void setUsuarioId(Integer usuarioId) {
		this.usuarioId = usuarioId;
	}

	@Column(name = "descripcion", length = 250)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "compartido", length = 1)
	public Character getCompartido() {
		return this.compartido;
	}

	public void setCompartido(Character compartido) {
		this.compartido = compartido;
	}

	@Column(name = "id_tipo")
	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "x", precision = 15, scale = 10)
	public BigDecimal getX() {
		return this.x;
	}

	public void setX(BigDecimal x) {
		this.x = x;
	}

	@Column(name = "y", precision = 15, scale = 10)
	public BigDecimal getY() {
		return this.y;
	}

	public void setY(BigDecimal y) {
		this.y = y;
	}

}
