package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TtrMetodosPago generated by hbm2java
 */
@Entity
@Table(name = "ttr_metodos_pago", catalog = "rutadb")
public class TtrMetodosPago implements java.io.Serializable {

	private Integer idMetodoPago;
	private String nombre;
	private String urlIcon;
	private Set<TtrMetodosCasetas> ttrMetodosCasetases = new HashSet<TtrMetodosCasetas>(
			0);

	public TtrMetodosPago() {
	}

	public TtrMetodosPago(String nombre) {
		this.nombre = nombre;
	}

	public TtrMetodosPago(String nombre, String urlIcon,
			Set<TtrMetodosCasetas> ttrMetodosCasetases) {
		this.nombre = nombre;
		this.urlIcon = urlIcon;
		this.ttrMetodosCasetases = ttrMetodosCasetases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_metodo_pago", unique = true, nullable = false)
	public Integer getIdMetodoPago() {
		return this.idMetodoPago;
	}

	public void setIdMetodoPago(Integer idMetodoPago) {
		this.idMetodoPago = idMetodoPago;
	}

	@Column(name = "nombre", nullable = false, length = 254)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url_icon", length = 254)
	public String getUrlIcon() {
		return this.urlIcon;
	}

	public void setUrlIcon(String urlIcon) {
		this.urlIcon = urlIcon;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrMetodosPago")
	public Set<TtrMetodosCasetas> getTtrMetodosCasetases() {
		return this.ttrMetodosCasetases;
	}

	public void setTtrMetodosCasetases(
			Set<TtrMetodosCasetas> ttrMetodosCasetases) {
		this.ttrMetodosCasetases = ttrMetodosCasetases;
	}

}
