package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrMetodosCasetasCombinada generated by hbm2java
 */
@Entity
@Table(name = "ttr_metodos_casetas_combinada", catalog = "rutadb")
public class TtrMetodosCasetasCombinada implements java.io.Serializable {

	private Integer idMetodoCasetaCombinada;
	private int fkIdMetodoPago;
	private int fkIdCasetaCombinada;

	public TtrMetodosCasetasCombinada() {
	}

	public TtrMetodosCasetasCombinada(int fkIdMetodoPago,
			int fkIdCasetaCombinada) {
		this.fkIdMetodoPago = fkIdMetodoPago;
		this.fkIdCasetaCombinada = fkIdCasetaCombinada;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_metodo_caseta_combinada", unique = true, nullable = false)
	public Integer getIdMetodoCasetaCombinada() {
		return this.idMetodoCasetaCombinada;
	}

	public void setIdMetodoCasetaCombinada(Integer idMetodoCasetaCombinada) {
		this.idMetodoCasetaCombinada = idMetodoCasetaCombinada;
	}

	@Column(name = "fk_id_metodo_pago", nullable = false)
	public int getFkIdMetodoPago() {
		return this.fkIdMetodoPago;
	}

	public void setFkIdMetodoPago(int fkIdMetodoPago) {
		this.fkIdMetodoPago = fkIdMetodoPago;
	}

	@Column(name = "fk_id_caseta_combinada", nullable = false)
	public int getFkIdCasetaCombinada() {
		return this.fkIdCasetaCombinada;
	}

	public void setFkIdCasetaCombinada(int fkIdCasetaCombinada) {
		this.fkIdCasetaCombinada = fkIdCasetaCombinada;
	}

}
