package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TtrMetodosCasetas generated by hbm2java
 */
@Entity
@Table(name = "ttr_metodos_casetas", catalog = "rutadb")
public class TtrMetodosCasetas implements java.io.Serializable {

	private Integer idMetodoCaseta;
	private TtrMetodosPago ttrMetodosPago;
	private int fkIdCaseta;

	public TtrMetodosCasetas() {
	}

	public TtrMetodosCasetas(TtrMetodosPago ttrMetodosPago, int fkIdCaseta) {
		this.ttrMetodosPago = ttrMetodosPago;
		this.fkIdCaseta = fkIdCaseta;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_metodo_caseta", unique = true, nullable = false)
	public Integer getIdMetodoCaseta() {
		return this.idMetodoCaseta;
	}

	public void setIdMetodoCaseta(Integer idMetodoCaseta) {
		this.idMetodoCaseta = idMetodoCaseta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "fk_id_metodo_pago", nullable = false)
	public TtrMetodosPago getTtrMetodosPago() {
		return this.ttrMetodosPago;
	}

	public void setTtrMetodosPago(TtrMetodosPago ttrMetodosPago) {
		this.ttrMetodosPago = ttrMetodosPago;
	}

	@Column(name = "fk_id_caseta", nullable = false)
	public int getFkIdCaseta() {
		return this.fkIdCaseta;
	}

	public void setFkIdCaseta(int fkIdCaseta) {
		this.fkIdCaseta = fkIdCaseta;
	}

}
