package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrPermisos generated by hbm2java
 */
@Entity
@Table(name = "ttr_permisos", catalog = "rutadb")
public class TtrPermisos implements java.io.Serializable {

	private Integer permisoId;
	private String tabla;
	private Integer rolId;
	private Integer permiso;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;

	public TtrPermisos() {
	}

	public TtrPermisos(String tabla, Integer rolId, Integer permiso,
			Date creadoEl, Date modificadoEl, String modificadoPor) {
		this.tabla = tabla;
		this.rolId = rolId;
		this.permiso = permiso;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "permiso_id", unique = true, nullable = false)
	public Integer getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(Integer permisoId) {
		this.permisoId = permisoId;
	}

	@Column(name = "tabla", length = 100)
	public String getTabla() {
		return this.tabla;
	}

	public void setTabla(String tabla) {
		this.tabla = tabla;
	}

	@Column(name = "rol_id")
	public Integer getRolId() {
		return this.rolId;
	}

	public void setRolId(Integer rolId) {
		this.rolId = rolId;
	}

	@Column(name = "permiso")
	public Integer getPermiso() {
		return this.permiso;
	}

	public void setPermiso(Integer permiso) {
		this.permiso = permiso;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

}
