package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrRelEdoRuta generated by hbm2java
 */
@Entity
@Table(name = "ttr_rel_edo_ruta", catalog = "rutadb")
public class TtrRelEdoRuta implements java.io.Serializable {

	private Integer idRelEdoRuta;
	private String cveOdEdo;
	private String clavesEdosRuta;
	private String cveDoEdo;

	public TtrRelEdoRuta() {
	}

	public TtrRelEdoRuta(String cveOdEdo, String clavesEdosRuta, String cveDoEdo) {
		this.cveOdEdo = cveOdEdo;
		this.clavesEdosRuta = clavesEdosRuta;
		this.cveDoEdo = cveDoEdo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_rel_edo_ruta", unique = true, nullable = false)
	public Integer getIdRelEdoRuta() {
		return this.idRelEdoRuta;
	}

	public void setIdRelEdoRuta(Integer idRelEdoRuta) {
		this.idRelEdoRuta = idRelEdoRuta;
	}

	@Column(name = "cve_od_edo", length = 4)
	public String getCveOdEdo() {
		return this.cveOdEdo;
	}

	public void setCveOdEdo(String cveOdEdo) {
		this.cveOdEdo = cveOdEdo;
	}

	@Column(name = "claves_edos_ruta", length = 700)
	public String getClavesEdosRuta() {
		return this.clavesEdosRuta;
	}

	public void setClavesEdosRuta(String clavesEdosRuta) {
		this.clavesEdosRuta = clavesEdosRuta;
	}

	@Column(name = "cve_do_edo", length = 4)
	public String getCveDoEdo() {
		return this.cveDoEdo;
	}

	public void setCveDoEdo(String cveDoEdo) {
		this.cveDoEdo = cveDoEdo;
	}

}
