package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrRoutesCacheId generated by hbm2java
 */
@Embeddable
public class TtrRoutesCacheId implements java.io.Serializable {

	private String origenX;
	private String origenY;
	private Long origenSource;
	private Long origenTarget;
	private String origenDesc;
	private Integer origenIdtramo;
	private String destinoX;
	private String destinoY;
	private Long destinoSource;
	private Long destinoTarget;
	private String destinoDesc;
	private Integer destinoIdtramo;
	private Integer tipoRuta;
	private Boolean opcionCaseta;
	private Boolean opcionAlerta;
	private Integer vehiculoTipo;
	private Integer vehiculoSubtipo;
	private BigDecimal vehiculoRendimiento;
	private BigDecimal vehiculoCostoltgas;
	private Date fechaCreacion;
	private String json;
	private Integer excedente;
	private byte[] rutaSerializada;

	public TtrRoutesCacheId() {
	}

	public TtrRoutesCacheId(String origenX, String origenY, Long origenSource,
			Long origenTarget, String origenDesc, Integer origenIdtramo,
			String destinoX, String destinoY, Long destinoSource,
			Long destinoTarget, String destinoDesc, Integer destinoIdtramo,
			Integer tipoRuta, Boolean opcionCaseta, Boolean opcionAlerta,
			Integer vehiculoTipo, Integer vehiculoSubtipo,
			BigDecimal vehiculoRendimiento, BigDecimal vehiculoCostoltgas,
			Date fechaCreacion, String json, Integer excedente,
			byte[] rutaSerializada) {
		this.origenX = origenX;
		this.origenY = origenY;
		this.origenSource = origenSource;
		this.origenTarget = origenTarget;
		this.origenDesc = origenDesc;
		this.origenIdtramo = origenIdtramo;
		this.destinoX = destinoX;
		this.destinoY = destinoY;
		this.destinoSource = destinoSource;
		this.destinoTarget = destinoTarget;
		this.destinoDesc = destinoDesc;
		this.destinoIdtramo = destinoIdtramo;
		this.tipoRuta = tipoRuta;
		this.opcionCaseta = opcionCaseta;
		this.opcionAlerta = opcionAlerta;
		this.vehiculoTipo = vehiculoTipo;
		this.vehiculoSubtipo = vehiculoSubtipo;
		this.vehiculoRendimiento = vehiculoRendimiento;
		this.vehiculoCostoltgas = vehiculoCostoltgas;
		this.fechaCreacion = fechaCreacion;
		this.json = json;
		this.excedente = excedente;
		this.rutaSerializada = rutaSerializada;
	}

	@Column(name = "origen_x", length = 50)
	public String getOrigenX() {
		return this.origenX;
	}

	public void setOrigenX(String origenX) {
		this.origenX = origenX;
	}

	@Column(name = "origen_y", length = 50)
	public String getOrigenY() {
		return this.origenY;
	}

	public void setOrigenY(String origenY) {
		this.origenY = origenY;
	}

	@Column(name = "origen_source")
	public Long getOrigenSource() {
		return this.origenSource;
	}

	public void setOrigenSource(Long origenSource) {
		this.origenSource = origenSource;
	}

	@Column(name = "origen_target")
	public Long getOrigenTarget() {
		return this.origenTarget;
	}

	public void setOrigenTarget(Long origenTarget) {
		this.origenTarget = origenTarget;
	}

	@Column(name = "origen_desc", length = 400)
	public String getOrigenDesc() {
		return this.origenDesc;
	}

	public void setOrigenDesc(String origenDesc) {
		this.origenDesc = origenDesc;
	}

	@Column(name = "origen_idtramo")
	public Integer getOrigenIdtramo() {
		return this.origenIdtramo;
	}

	public void setOrigenIdtramo(Integer origenIdtramo) {
		this.origenIdtramo = origenIdtramo;
	}

	@Column(name = "destino_x", length = 50)
	public String getDestinoX() {
		return this.destinoX;
	}

	public void setDestinoX(String destinoX) {
		this.destinoX = destinoX;
	}

	@Column(name = "destino_y", length = 50)
	public String getDestinoY() {
		return this.destinoY;
	}

	public void setDestinoY(String destinoY) {
		this.destinoY = destinoY;
	}

	@Column(name = "destino_source")
	public Long getDestinoSource() {
		return this.destinoSource;
	}

	public void setDestinoSource(Long destinoSource) {
		this.destinoSource = destinoSource;
	}

	@Column(name = "destino_target")
	public Long getDestinoTarget() {
		return this.destinoTarget;
	}

	public void setDestinoTarget(Long destinoTarget) {
		this.destinoTarget = destinoTarget;
	}

	@Column(name = "destino_desc", length = 400)
	public String getDestinoDesc() {
		return this.destinoDesc;
	}

	public void setDestinoDesc(String destinoDesc) {
		this.destinoDesc = destinoDesc;
	}

	@Column(name = "destino_idtramo")
	public Integer getDestinoIdtramo() {
		return this.destinoIdtramo;
	}

	public void setDestinoIdtramo(Integer destinoIdtramo) {
		this.destinoIdtramo = destinoIdtramo;
	}

	@Column(name = "tipo_ruta")
	public Integer getTipoRuta() {
		return this.tipoRuta;
	}

	public void setTipoRuta(Integer tipoRuta) {
		this.tipoRuta = tipoRuta;
	}

	@Column(name = "opcion_caseta")
	public Boolean getOpcionCaseta() {
		return this.opcionCaseta;
	}

	public void setOpcionCaseta(Boolean opcionCaseta) {
		this.opcionCaseta = opcionCaseta;
	}

	@Column(name = "opcion_alerta")
	public Boolean getOpcionAlerta() {
		return this.opcionAlerta;
	}

	public void setOpcionAlerta(Boolean opcionAlerta) {
		this.opcionAlerta = opcionAlerta;
	}

	@Column(name = "vehiculo_tipo")
	public Integer getVehiculoTipo() {
		return this.vehiculoTipo;
	}

	public void setVehiculoTipo(Integer vehiculoTipo) {
		this.vehiculoTipo = vehiculoTipo;
	}

	@Column(name = "vehiculo_subtipo")
	public Integer getVehiculoSubtipo() {
		return this.vehiculoSubtipo;
	}

	public void setVehiculoSubtipo(Integer vehiculoSubtipo) {
		this.vehiculoSubtipo = vehiculoSubtipo;
	}

	@Column(name = "vehiculo_rendimiento", precision = 10)
	public BigDecimal getVehiculoRendimiento() {
		return this.vehiculoRendimiento;
	}

	public void setVehiculoRendimiento(BigDecimal vehiculoRendimiento) {
		this.vehiculoRendimiento = vehiculoRendimiento;
	}

	@Column(name = "vehiculo_costoltgas", precision = 10)
	public BigDecimal getVehiculoCostoltgas() {
		return this.vehiculoCostoltgas;
	}

	public void setVehiculoCostoltgas(BigDecimal vehiculoCostoltgas) {
		this.vehiculoCostoltgas = vehiculoCostoltgas;
	}

	@Column(name = "fecha_creacion", length = 0)
	public Date getFechaCreacion() {
		return this.fechaCreacion;
	}

	public void setFechaCreacion(Date fechaCreacion) {
		this.fechaCreacion = fechaCreacion;
	}

	@Column(name = "json", length = 65535)
	public String getJson() {
		return this.json;
	}

	public void setJson(String json) {
		this.json = json;
	}

	@Column(name = "excedente")
	public Integer getExcedente() {
		return this.excedente;
	}

	public void setExcedente(Integer excedente) {
		this.excedente = excedente;
	}

	@Column(name = "ruta_serializada")
	public byte[] getRutaSerializada() {
		return this.rutaSerializada;
	}

	public void setRutaSerializada(byte[] rutaSerializada) {
		this.rutaSerializada = rutaSerializada;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrRoutesCacheId))
			return false;
		TtrRoutesCacheId castOther = (TtrRoutesCacheId) other;

		return ((this.getOrigenX() == castOther.getOrigenX()) || (this
				.getOrigenX() != null && castOther.getOrigenX() != null && this
				.getOrigenX().equals(castOther.getOrigenX())))
				&& ((this.getOrigenY() == castOther.getOrigenY()) || (this
						.getOrigenY() != null && castOther.getOrigenY() != null && this
						.getOrigenY().equals(castOther.getOrigenY())))
				&& ((this.getOrigenSource() == castOther.getOrigenSource()) || (this
						.getOrigenSource() != null
						&& castOther.getOrigenSource() != null && this
						.getOrigenSource().equals(castOther.getOrigenSource())))
				&& ((this.getOrigenTarget() == castOther.getOrigenTarget()) || (this
						.getOrigenTarget() != null
						&& castOther.getOrigenTarget() != null && this
						.getOrigenTarget().equals(castOther.getOrigenTarget())))
				&& ((this.getOrigenDesc() == castOther.getOrigenDesc()) || (this
						.getOrigenDesc() != null
						&& castOther.getOrigenDesc() != null && this
						.getOrigenDesc().equals(castOther.getOrigenDesc())))
				&& ((this.getOrigenIdtramo() == castOther.getOrigenIdtramo()) || (this
						.getOrigenIdtramo() != null
						&& castOther.getOrigenIdtramo() != null && this
						.getOrigenIdtramo()
						.equals(castOther.getOrigenIdtramo())))
				&& ((this.getDestinoX() == castOther.getDestinoX()) || (this
						.getDestinoX() != null
						&& castOther.getDestinoX() != null && this
						.getDestinoX().equals(castOther.getDestinoX())))
				&& ((this.getDestinoY() == castOther.getDestinoY()) || (this
						.getDestinoY() != null
						&& castOther.getDestinoY() != null && this
						.getDestinoY().equals(castOther.getDestinoY())))
				&& ((this.getDestinoSource() == castOther.getDestinoSource()) || (this
						.getDestinoSource() != null
						&& castOther.getDestinoSource() != null && this
						.getDestinoSource()
						.equals(castOther.getDestinoSource())))
				&& ((this.getDestinoTarget() == castOther.getDestinoTarget()) || (this
						.getDestinoTarget() != null
						&& castOther.getDestinoTarget() != null && this
						.getDestinoTarget()
						.equals(castOther.getDestinoTarget())))
				&& ((this.getDestinoDesc() == castOther.getDestinoDesc()) || (this
						.getDestinoDesc() != null
						&& castOther.getDestinoDesc() != null && this
						.getDestinoDesc().equals(castOther.getDestinoDesc())))
				&& ((this.getDestinoIdtramo() == castOther.getDestinoIdtramo()) || (this
						.getDestinoIdtramo() != null
						&& castOther.getDestinoIdtramo() != null && this
						.getDestinoIdtramo().equals(
								castOther.getDestinoIdtramo())))
				&& ((this.getTipoRuta() == castOther.getTipoRuta()) || (this
						.getTipoRuta() != null
						&& castOther.getTipoRuta() != null && this
						.getTipoRuta().equals(castOther.getTipoRuta())))
				&& ((this.getOpcionCaseta() == castOther.getOpcionCaseta()) || (this
						.getOpcionCaseta() != null
						&& castOther.getOpcionCaseta() != null && this
						.getOpcionCaseta().equals(castOther.getOpcionCaseta())))
				&& ((this.getOpcionAlerta() == castOther.getOpcionAlerta()) || (this
						.getOpcionAlerta() != null
						&& castOther.getOpcionAlerta() != null && this
						.getOpcionAlerta().equals(castOther.getOpcionAlerta())))
				&& ((this.getVehiculoTipo() == castOther.getVehiculoTipo()) || (this
						.getVehiculoTipo() != null
						&& castOther.getVehiculoTipo() != null && this
						.getVehiculoTipo().equals(castOther.getVehiculoTipo())))
				&& ((this.getVehiculoSubtipo() == castOther
						.getVehiculoSubtipo()) || (this.getVehiculoSubtipo() != null
						&& castOther.getVehiculoSubtipo() != null && this
						.getVehiculoSubtipo().equals(
								castOther.getVehiculoSubtipo())))
				&& ((this.getVehiculoRendimiento() == castOther
						.getVehiculoRendimiento()) || (this
						.getVehiculoRendimiento() != null
						&& castOther.getVehiculoRendimiento() != null && this
						.getVehiculoRendimiento().equals(
								castOther.getVehiculoRendimiento())))
				&& ((this.getVehiculoCostoltgas() == castOther
						.getVehiculoCostoltgas()) || (this
						.getVehiculoCostoltgas() != null
						&& castOther.getVehiculoCostoltgas() != null && this
						.getVehiculoCostoltgas().equals(
								castOther.getVehiculoCostoltgas())))
				&& ((this.getFechaCreacion() == castOther.getFechaCreacion()) || (this
						.getFechaCreacion() != null
						&& castOther.getFechaCreacion() != null && this
						.getFechaCreacion()
						.equals(castOther.getFechaCreacion())))
				&& ((this.getJson() == castOther.getJson()) || (this.getJson() != null
						&& castOther.getJson() != null && this.getJson()
						.equals(castOther.getJson())))
				&& ((this.getExcedente() == castOther.getExcedente()) || (this
						.getExcedente() != null
						&& castOther.getExcedente() != null && this
						.getExcedente().equals(castOther.getExcedente())))
				&& ((this.getRutaSerializada() == castOther
						.getRutaSerializada()) || (this.getRutaSerializada() != null
						&& castOther.getRutaSerializada() != null && Arrays
							.equals(this.getRutaSerializada(),
									castOther.getRutaSerializada())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getOrigenX() == null ? 0 : this.getOrigenX().hashCode());
		result = 37 * result
				+ (getOrigenY() == null ? 0 : this.getOrigenY().hashCode());
		result = 37
				* result
				+ (getOrigenSource() == null ? 0 : this.getOrigenSource()
						.hashCode());
		result = 37
				* result
				+ (getOrigenTarget() == null ? 0 : this.getOrigenTarget()
						.hashCode());
		result = 37
				* result
				+ (getOrigenDesc() == null ? 0 : this.getOrigenDesc()
						.hashCode());
		result = 37
				* result
				+ (getOrigenIdtramo() == null ? 0 : this.getOrigenIdtramo()
						.hashCode());
		result = 37 * result
				+ (getDestinoX() == null ? 0 : this.getDestinoX().hashCode());
		result = 37 * result
				+ (getDestinoY() == null ? 0 : this.getDestinoY().hashCode());
		result = 37
				* result
				+ (getDestinoSource() == null ? 0 : this.getDestinoSource()
						.hashCode());
		result = 37
				* result
				+ (getDestinoTarget() == null ? 0 : this.getDestinoTarget()
						.hashCode());
		result = 37
				* result
				+ (getDestinoDesc() == null ? 0 : this.getDestinoDesc()
						.hashCode());
		result = 37
				* result
				+ (getDestinoIdtramo() == null ? 0 : this.getDestinoIdtramo()
						.hashCode());
		result = 37 * result
				+ (getTipoRuta() == null ? 0 : this.getTipoRuta().hashCode());
		result = 37
				* result
				+ (getOpcionCaseta() == null ? 0 : this.getOpcionCaseta()
						.hashCode());
		result = 37
				* result
				+ (getOpcionAlerta() == null ? 0 : this.getOpcionAlerta()
						.hashCode());
		result = 37
				* result
				+ (getVehiculoTipo() == null ? 0 : this.getVehiculoTipo()
						.hashCode());
		result = 37
				* result
				+ (getVehiculoSubtipo() == null ? 0 : this.getVehiculoSubtipo()
						.hashCode());
		result = 37
				* result
				+ (getVehiculoRendimiento() == null ? 0 : this
						.getVehiculoRendimiento().hashCode());
		result = 37
				* result
				+ (getVehiculoCostoltgas() == null ? 0 : this
						.getVehiculoCostoltgas().hashCode());
		result = 37
				* result
				+ (getFechaCreacion() == null ? 0 : this.getFechaCreacion()
						.hashCode());
		result = 37 * result
				+ (getJson() == null ? 0 : this.getJson().hashCode());
		result = 37 * result
				+ (getExcedente() == null ? 0 : this.getExcedente().hashCode());
		result = 37
				* result
				+ (getRutaSerializada() == null ? 0 : Arrays.hashCode(this
						.getRutaSerializada()));
		return result;
	}

}
