package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TtrResistenciaId generated by hbm2java
 */
@Embeddable
public class TtrResistenciaId implements java.io.Serializable {

	private int idResistencia;
	private String nombreResistencia;
	private String campoTtrGrafoResistencia;
	private String campoTtrGrafoResistenciaInvertida;

	public TtrResistenciaId() {
	}

	public TtrResistenciaId(int idResistencia) {
		this.idResistencia = idResistencia;
	}

	public TtrResistenciaId(int idResistencia, String nombreResistencia,
			String campoTtrGrafoResistencia,
			String campoTtrGrafoResistenciaInvertida) {
		this.idResistencia = idResistencia;
		this.nombreResistencia = nombreResistencia;
		this.campoTtrGrafoResistencia = campoTtrGrafoResistencia;
		this.campoTtrGrafoResistenciaInvertida = campoTtrGrafoResistenciaInvertida;
	}

	@Column(name = "id_resistencia", nullable = false)
	public int getIdResistencia() {
		return this.idResistencia;
	}

	public void setIdResistencia(int idResistencia) {
		this.idResistencia = idResistencia;
	}

	@Column(name = "nombre_resistencia", length = 200)
	public String getNombreResistencia() {
		return this.nombreResistencia;
	}

	public void setNombreResistencia(String nombreResistencia) {
		this.nombreResistencia = nombreResistencia;
	}

	@Column(name = "campo_ttr_grafo_resistencia", length = 50)
	public String getCampoTtrGrafoResistencia() {
		return this.campoTtrGrafoResistencia;
	}

	public void setCampoTtrGrafoResistencia(String campoTtrGrafoResistencia) {
		this.campoTtrGrafoResistencia = campoTtrGrafoResistencia;
	}

	@Column(name = "campo_ttr_grafo_resistencia_invertida", length = 50)
	public String getCampoTtrGrafoResistenciaInvertida() {
		return this.campoTtrGrafoResistenciaInvertida;
	}

	public void setCampoTtrGrafoResistenciaInvertida(
			String campoTtrGrafoResistenciaInvertida) {
		this.campoTtrGrafoResistenciaInvertida = campoTtrGrafoResistenciaInvertida;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TtrResistenciaId))
			return false;
		TtrResistenciaId castOther = (TtrResistenciaId) other;

		return (this.getIdResistencia() == castOther.getIdResistencia())
				&& ((this.getNombreResistencia() == castOther
						.getNombreResistencia()) || (this
						.getNombreResistencia() != null
						&& castOther.getNombreResistencia() != null && this
						.getNombreResistencia().equals(
								castOther.getNombreResistencia())))
				&& ((this.getCampoTtrGrafoResistencia() == castOther
						.getCampoTtrGrafoResistencia()) || (this
						.getCampoTtrGrafoResistencia() != null
						&& castOther.getCampoTtrGrafoResistencia() != null && this
						.getCampoTtrGrafoResistencia().equals(
								castOther.getCampoTtrGrafoResistencia())))
				&& ((this.getCampoTtrGrafoResistenciaInvertida() == castOther
						.getCampoTtrGrafoResistenciaInvertida()) || (this
						.getCampoTtrGrafoResistenciaInvertida() != null
						&& castOther.getCampoTtrGrafoResistenciaInvertida() != null && this
						.getCampoTtrGrafoResistenciaInvertida()
						.equals(castOther
								.getCampoTtrGrafoResistenciaInvertida())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdResistencia();
		result = 37
				* result
				+ (getNombreResistencia() == null ? 0 : this
						.getNombreResistencia().hashCode());
		result = 37
				* result
				+ (getCampoTtrGrafoResistencia() == null ? 0 : this
						.getCampoTtrGrafoResistencia().hashCode());
		result = 37
				* result
				+ (getCampoTtrGrafoResistenciaInvertida() == null ? 0 : this
						.getCampoTtrGrafoResistenciaInvertida().hashCode());
		return result;
	}

}
