package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TtrRoutesCacheTmp generated by hbm2java
 */
@Entity
@Table(name = "ttr_routes_cache_tmp", catalog = "rutadb")
public class TtrRoutesCacheTmp implements java.io.Serializable {

	private TtrRoutesCacheTmpId id;

	public TtrRoutesCacheTmp() {
	}

	public TtrRoutesCacheTmp(TtrRoutesCacheTmpId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "origenX", column = @Column(name = "origen_x", length = 50)),
			@AttributeOverride(name = "origenY", column = @Column(name = "origen_y", length = 50)),
			@AttributeOverride(name = "origenSource", column = @Column(name = "origen_source")),
			@AttributeOverride(name = "origenTarget", column = @Column(name = "origen_target")),
			@AttributeOverride(name = "origenDesc", column = @Column(name = "origen_desc", length = 400)),
			@AttributeOverride(name = "origenIdtramo", column = @Column(name = "origen_idtramo")),
			@AttributeOverride(name = "destinoX", column = @Column(name = "destino_x", length = 50)),
			@AttributeOverride(name = "destinoY", column = @Column(name = "destino_y", length = 50)),
			@AttributeOverride(name = "destinoSource", column = @Column(name = "destino_source")),
			@AttributeOverride(name = "destinoTarget", column = @Column(name = "destino_target")),
			@AttributeOverride(name = "destinoDesc", column = @Column(name = "destino_desc", length = 400)),
			@AttributeOverride(name = "destinoIdtramo", column = @Column(name = "destino_idtramo")),
			@AttributeOverride(name = "tipoRuta", column = @Column(name = "tipo_ruta")),
			@AttributeOverride(name = "opcionCaseta", column = @Column(name = "opcion_caseta")),
			@AttributeOverride(name = "opcionAlerta", column = @Column(name = "opcion_alerta")),
			@AttributeOverride(name = "vehiculoTipo", column = @Column(name = "vehiculo_tipo")),
			@AttributeOverride(name = "vehiculoSubtipo", column = @Column(name = "vehiculo_subtipo")),
			@AttributeOverride(name = "vehiculoRendimiento", column = @Column(name = "vehiculo_rendimiento", precision = 10)),
			@AttributeOverride(name = "vehiculoCostoltgas", column = @Column(name = "vehiculo_costoltgas", precision = 10)),
			@AttributeOverride(name = "fechaCreacion", column = @Column(name = "fecha_creacion", length = 0)),
			@AttributeOverride(name = "json", column = @Column(name = "json", length = 65535)),
			@AttributeOverride(name = "excedente", column = @Column(name = "excedente")) })
	public TtrRoutesCacheTmpId getId() {
		return this.id;
	}

	public void setId(TtrRoutesCacheTmpId id) {
		this.id = id;
	}

}
