package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * TtrResistencia generated by hbm2java
 */
@Entity
@Table(name = "ttr_resistencia", catalog = "rutadb")
public class TtrResistencia implements java.io.Serializable {

	private TtrResistenciaId id;

	public TtrResistencia() {
	}

	public TtrResistencia(TtrResistenciaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idResistencia", column = @Column(name = "id_resistencia", nullable = false)),
			@AttributeOverride(name = "nombreResistencia", column = @Column(name = "nombre_resistencia", length = 200)),
			@AttributeOverride(name = "campoTtrGrafoResistencia", column = @Column(name = "campo_ttr_grafo_resistencia", length = 50)),
			@AttributeOverride(name = "campoTtrGrafoResistenciaInvertida", column = @Column(name = "campo_ttr_grafo_resistencia_invertida", length = 50)) })
	public TtrResistenciaId getId() {
		return this.id;
	}

	public void setId(TtrResistenciaId id) {
		this.id = id;
	}

}
