package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrSubTiposVehiculo generated by hbm2java
 */
@Entity
@Table(name = "ttr_sub_tipos_vehiculo", catalog = "rutadb")
public class TtrSubTiposVehiculo implements java.io.Serializable {

	private int idSubTipoVehiculo;
	private TtrTiposVehiculo ttrTiposVehiculo;
	private String nombre;
	private BigDecimal rendimientoPorLitro;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;
	private Set<TtrCostosCaseta> ttrCostosCasetas = new HashSet<TtrCostosCaseta>(
			0);

	public TtrSubTiposVehiculo() {
	}

	public TtrSubTiposVehiculo(int idSubTipoVehiculo) {
		this.idSubTipoVehiculo = idSubTipoVehiculo;
	}

	public TtrSubTiposVehiculo(int idSubTipoVehiculo,
			TtrTiposVehiculo ttrTiposVehiculo, String nombre,
			BigDecimal rendimientoPorLitro, Date creadoEl, Date modificadoEl,
			String modificadoPor, Set<TtrCostosCaseta> ttrCostosCasetas) {
		this.idSubTipoVehiculo = idSubTipoVehiculo;
		this.ttrTiposVehiculo = ttrTiposVehiculo;
		this.nombre = nombre;
		this.rendimientoPorLitro = rendimientoPorLitro;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
		this.ttrCostosCasetas = ttrCostosCasetas;
	}

	@Id
	@Column(name = "id_sub_tipo_vehiculo", unique = true, nullable = false)
	public int getIdSubTipoVehiculo() {
		return this.idSubTipoVehiculo;
	}

	public void setIdSubTipoVehiculo(int idSubTipoVehiculo) {
		this.idSubTipoVehiculo = idSubTipoVehiculo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_tipo_vehiculo")
	public TtrTiposVehiculo getTtrTiposVehiculo() {
		return this.ttrTiposVehiculo;
	}

	public void setTtrTiposVehiculo(TtrTiposVehiculo ttrTiposVehiculo) {
		this.ttrTiposVehiculo = ttrTiposVehiculo;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "rendimiento_por_litro", precision = 10)
	public BigDecimal getRendimientoPorLitro() {
		return this.rendimientoPorLitro;
	}

	public void setRendimientoPorLitro(BigDecimal rendimientoPorLitro) {
		this.rendimientoPorLitro = rendimientoPorLitro;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrSubTiposVehiculo")
	public Set<TtrCostosCaseta> getTtrCostosCasetas() {
		return this.ttrCostosCasetas;
	}

	public void setTtrCostosCasetas(Set<TtrCostosCaseta> ttrCostosCasetas) {
		this.ttrCostosCasetas = ttrCostosCasetas;
	}

}
