package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrTiposCombustible generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_combustible", catalog = "rutadb")
public class TtrTiposCombustible implements java.io.Serializable {

	private int idTipoCombustible;
	private String nombre;
	private String urlIcono;
	private BigDecimal costoPorLitro;
	private String clave;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;

	public TtrTiposCombustible() {
	}

	public TtrTiposCombustible(int idTipoCombustible) {
		this.idTipoCombustible = idTipoCombustible;
	}

	public TtrTiposCombustible(int idTipoCombustible, String nombre,
			String urlIcono, BigDecimal costoPorLitro, String clave,
			Date creadoEl, Date modificadoEl, String modificadoPor) {
		this.idTipoCombustible = idTipoCombustible;
		this.nombre = nombre;
		this.urlIcono = urlIcono;
		this.costoPorLitro = costoPorLitro;
		this.clave = clave;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
	}

	@Id
	@Column(name = "id_tipo_combustible", unique = true, nullable = false)
	public int getIdTipoCombustible() {
		return this.idTipoCombustible;
	}

	public void setIdTipoCombustible(int idTipoCombustible) {
		this.idTipoCombustible = idTipoCombustible;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "url_icono", length = 150)
	public String getUrlIcono() {
		return this.urlIcono;
	}

	public void setUrlIcono(String urlIcono) {
		this.urlIcono = urlIcono;
	}

	@Column(name = "costo_por_litro", precision = 10)
	public BigDecimal getCostoPorLitro() {
		return this.costoPorLitro;
	}

	public void setCostoPorLitro(BigDecimal costoPorLitro) {
		this.costoPorLitro = costoPorLitro;
	}

	@Column(name = "clave", length = 10)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

}
