package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrTiposDeMarcadores generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_de_marcadores", catalog = "rutadb")
public class TtrTiposDeMarcadores implements java.io.Serializable {

	private Integer tipoDeMarcadorId;
	private String tipoDeMarcador;
	private String codigo;
	private String iconoUrl;
	private Boolean activo;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;

	public TtrTiposDeMarcadores() {
	}

	public TtrTiposDeMarcadores(String codigo, String iconoUrl) {
		this.codigo = codigo;
		this.iconoUrl = iconoUrl;
	}

	public TtrTiposDeMarcadores(String tipoDeMarcador, String codigo,
			String iconoUrl, Boolean activo, Date creadoEl, Date modificadoEl,
			String modificadoPor) {
		this.tipoDeMarcador = tipoDeMarcador;
		this.codigo = codigo;
		this.iconoUrl = iconoUrl;
		this.activo = activo;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipo_de_marcador_id", unique = true, nullable = false)
	public Integer getTipoDeMarcadorId() {
		return this.tipoDeMarcadorId;
	}

	public void setTipoDeMarcadorId(Integer tipoDeMarcadorId) {
		this.tipoDeMarcadorId = tipoDeMarcadorId;
	}

	@Column(name = "tipo_de_marcador", length = 50)
	public String getTipoDeMarcador() {
		return this.tipoDeMarcador;
	}

	public void setTipoDeMarcador(String tipoDeMarcador) {
		this.tipoDeMarcador = tipoDeMarcador;
	}

	@Column(name = "codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "icono_url", nullable = false, length = 150)
	public String getIconoUrl() {
		return this.iconoUrl;
	}

	public void setIconoUrl(String iconoUrl) {
		this.iconoUrl = iconoUrl;
	}

	@Column(name = "activo")
	public Boolean getActivo() {
		return this.activo;
	}

	public void setActivo(Boolean activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

}
