package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrTiposVehiculo generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_vehiculo", catalog = "rutadb")
public class TtrTiposVehiculo implements java.io.Serializable {

	private int idTipoVehiculo;
	private String nombre;
	private String clave;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;
	private Set<TtrSubTiposVehiculo> ttrSubTiposVehiculos = new HashSet<TtrSubTiposVehiculo>(
			0);

	public TtrTiposVehiculo() {
	}

	public TtrTiposVehiculo(int idTipoVehiculo) {
		this.idTipoVehiculo = idTipoVehiculo;
	}

	public TtrTiposVehiculo(int idTipoVehiculo, String nombre, String clave,
			Date creadoEl, Date modificadoEl, String modificadoPor,
			Set<TtrSubTiposVehiculo> ttrSubTiposVehiculos) {
		this.idTipoVehiculo = idTipoVehiculo;
		this.nombre = nombre;
		this.clave = clave;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
		this.ttrSubTiposVehiculos = ttrSubTiposVehiculos;
	}

	@Id
	@Column(name = "id_tipo_vehiculo", unique = true, nullable = false)
	public int getIdTipoVehiculo() {
		return this.idTipoVehiculo;
	}

	public void setIdTipoVehiculo(int idTipoVehiculo) {
		this.idTipoVehiculo = idTipoVehiculo;
	}

	@Column(name = "nombre", length = 150)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "clave", length = 10)
	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrTiposVehiculo")
	public Set<TtrSubTiposVehiculo> getTtrSubTiposVehiculos() {
		return this.ttrSubTiposVehiculos;
	}

	public void setTtrSubTiposVehiculos(
			Set<TtrSubTiposVehiculo> ttrSubTiposVehiculos) {
		this.ttrSubTiposVehiculos = ttrSubTiposVehiculos;
	}

}
