package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrTiposDeAlertas generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_de_alertas", catalog = "rutadb")
public class TtrTiposDeAlertas implements java.io.Serializable {

	private Integer tipoDeAlertaId;
	private String tipoDeAlerta;
	private boolean activo;
	private String codigo;
	private String iconoUrl;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;
	private Set<TtrSubtiposDeAlertas> ttrSubtiposDeAlertases = new HashSet<TtrSubtiposDeAlertas>(
			0);

	public TtrTiposDeAlertas() {
	}

	public TtrTiposDeAlertas(boolean activo, String codigo, String iconoUrl) {
		this.activo = activo;
		this.codigo = codigo;
		this.iconoUrl = iconoUrl;
	}

	public TtrTiposDeAlertas(String tipoDeAlerta, boolean activo,
			String codigo, String iconoUrl, Date creadoEl, Date modificadoEl,
			String modificadoPor,
			Set<TtrSubtiposDeAlertas> ttrSubtiposDeAlertases) {
		this.tipoDeAlerta = tipoDeAlerta;
		this.activo = activo;
		this.codigo = codigo;
		this.iconoUrl = iconoUrl;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
		this.ttrSubtiposDeAlertases = ttrSubtiposDeAlertases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipo_de_alerta_id", unique = true, nullable = false)
	public Integer getTipoDeAlertaId() {
		return this.tipoDeAlertaId;
	}

	public void setTipoDeAlertaId(Integer tipoDeAlertaId) {
		this.tipoDeAlertaId = tipoDeAlertaId;
	}

	@Column(name = "tipo_de_alerta", length = 50)
	public String getTipoDeAlerta() {
		return this.tipoDeAlerta;
	}

	public void setTipoDeAlerta(String tipoDeAlerta) {
		this.tipoDeAlerta = tipoDeAlerta;
	}

	@Column(name = "activo", nullable = false)
	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	@Column(name = "codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "icono_url", nullable = false, length = 150)
	public String getIconoUrl() {
		return this.iconoUrl;
	}

	public void setIconoUrl(String iconoUrl) {
		this.iconoUrl = iconoUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ttrTiposDeAlertas")
	public Set<TtrSubtiposDeAlertas> getTtrSubtiposDeAlertases() {
		return this.ttrSubtiposDeAlertases;
	}

	public void setTtrSubtiposDeAlertases(
			Set<TtrSubtiposDeAlertas> ttrSubtiposDeAlertases) {
		this.ttrSubtiposDeAlertases = ttrSubtiposDeAlertases;
	}

}
