package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrTipoIncidencia generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipo_incidencia", catalog = "rutadb")
public class TtrTipoIncidencia implements java.io.Serializable {

	private int tipoIncidenciaId;
	private String descripcion;
	private String contingencia;

	public TtrTipoIncidencia() {
	}

	public TtrTipoIncidencia(int tipoIncidenciaId) {
		this.tipoIncidenciaId = tipoIncidenciaId;
	}

	public TtrTipoIncidencia(int tipoIncidenciaId, String descripcion,
			String contingencia) {
		this.tipoIncidenciaId = tipoIncidenciaId;
		this.descripcion = descripcion;
		this.contingencia = contingencia;
	}

	@Id
	@Column(name = "tipo_incidencia_id", unique = true, nullable = false)
	public int getTipoIncidenciaId() {
		return this.tipoIncidenciaId;
	}

	public void setTipoIncidenciaId(int tipoIncidenciaId) {
		this.tipoIncidenciaId = tipoIncidenciaId;
	}

	@Column(name = "descripcion", length = 50)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "contingencia", length = 250)
	public String getContingencia() {
		return this.contingencia;
	}

	public void setContingencia(String contingencia) {
		this.contingencia = contingencia;
	}

}
