package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrTiposDeImpacto generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_de_impacto", catalog = "rutadb")
public class TtrTiposDeImpacto implements java.io.Serializable {

	private Integer tipoDeImpactoId;
	private String tipoDeImpacto;

	public TtrTiposDeImpacto() {
	}

	public TtrTiposDeImpacto(String tipoDeImpacto) {
		this.tipoDeImpacto = tipoDeImpacto;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipo_de_impacto_id", unique = true, nullable = false)
	public Integer getTipoDeImpactoId() {
		return this.tipoDeImpactoId;
	}

	public void setTipoDeImpactoId(Integer tipoDeImpactoId) {
		this.tipoDeImpactoId = tipoDeImpactoId;
	}

	@Column(name = "tipo_de_impacto", nullable = false, length = 100)
	public String getTipoDeImpacto() {
		return this.tipoDeImpacto;
	}

	public void setTipoDeImpacto(String tipoDeImpacto) {
		this.tipoDeImpacto = tipoDeImpacto;
	}

}
