package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrTiposDePrioridad generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipos_de_prioridad", catalog = "rutadb")
public class TtrTiposDePrioridad implements java.io.Serializable {

	private Integer tipoDePrioridadId;
	private String tipoDePrioridad;

	public TtrTiposDePrioridad() {
	}

	public TtrTiposDePrioridad(String tipoDePrioridad) {
		this.tipoDePrioridad = tipoDePrioridad;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipo_de_prioridad_id", unique = true, nullable = false)
	public Integer getTipoDePrioridadId() {
		return this.tipoDePrioridadId;
	}

	public void setTipoDePrioridadId(Integer tipoDePrioridadId) {
		this.tipoDePrioridadId = tipoDePrioridadId;
	}

	@Column(name = "tipo_de_prioridad", nullable = false, length = 100)
	public String getTipoDePrioridad() {
		return this.tipoDePrioridad;
	}

	public void setTipoDePrioridad(String tipoDePrioridad) {
		this.tipoDePrioridad = tipoDePrioridad;
	}

}
