package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TtrTipoCondicion generated by hbm2java
 */
@Entity
@Table(name = "ttr_tipo_condicion", catalog = "rutadb")
public class TtrTipoCondicion implements java.io.Serializable {

	private long idTipoCondicion;
	private String nombre;

	public TtrTipoCondicion() {
	}

	public TtrTipoCondicion(long idTipoCondicion) {
		this.idTipoCondicion = idTipoCondicion;
	}

	public TtrTipoCondicion(long idTipoCondicion, String nombre) {
		this.idTipoCondicion = idTipoCondicion;
		this.nombre = nombre;
	}

	@Id
	@Column(name = "id_tipo_condicion", unique = true, nullable = false)
	public long getIdTipoCondicion() {
		return this.idTipoCondicion;
	}

	public void setIdTipoCondicion(long idTipoCondicion) {
		this.idTipoCondicion = idTipoCondicion;
	}

	@Column(name = "nombre", length = 7)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
