package mx.devhive.rutamx.entities;

// Generated 29/10/2014 12:40:55 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtrVariables generated by hbm2java
 */
@Entity
@Table(name = "ttr_variables", catalog = "rutadb")
public class TtrVariables implements java.io.Serializable {

	private int idVariable;
	private String codigo;
	private String descripcion;
	private String valor;
	private Date creadoEl;
	private Date modificadoEl;
	private String modificadoPor;
	private boolean publica;

	public TtrVariables() {
	}

	public TtrVariables(int idVariable, String codigo, String descripcion,
			String valor, boolean publica) {
		this.idVariable = idVariable;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.valor = valor;
		this.publica = publica;
	}

	public TtrVariables(int idVariable, String codigo, String descripcion,
			String valor, Date creadoEl, Date modificadoEl,
			String modificadoPor, boolean publica) {
		this.idVariable = idVariable;
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.valor = valor;
		this.creadoEl = creadoEl;
		this.modificadoEl = modificadoEl;
		this.modificadoPor = modificadoPor;
		this.publica = publica;
	}

	@Id
	@Column(name = "id_variable", unique = true, nullable = false)
	public int getIdVariable() {
		return this.idVariable;
	}

	public void setIdVariable(int idVariable) {
		this.idVariable = idVariable;
	}

	@Column(name = "codigo", nullable = false, length = 50)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", nullable = false, length = 150)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "valor", nullable = false, length = 1500)
	public String getValor() {
		return this.valor;
	}

	public void setValor(String valor) {
		this.valor = valor;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "creado_el", length = 0)
	public Date getCreadoEl() {
		return this.creadoEl;
	}

	public void setCreadoEl(Date creadoEl) {
		this.creadoEl = creadoEl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modificado_el", length = 0)
	public Date getModificadoEl() {
		return this.modificadoEl;
	}

	public void setModificadoEl(Date modificadoEl) {
		this.modificadoEl = modificadoEl;
	}

	@Column(name = "modificado_por", length = 50)
	public String getModificadoPor() {
		return this.modificadoPor;
	}

	public void setModificadoPor(String modificadoPor) {
		this.modificadoPor = modificadoPor;
	}

	@Column(name = "publica", nullable = false)
	public boolean isPublica() {
		return this.publica;
	}

	public void setPublica(boolean publica) {
		this.publica = publica;
	}

}
